import { LineEdit } from "std-widgets.slint";

export component InputWindow inherits Window {
    width: 800px;
    height: 80px;

    title: "Latchnott";
    background: #1E2650;
    always-on-top: true;
    forward-focus: input;

    callback save-note(string);
    callback cancel-note();
    callback focus-input();

    in-out property <string> text: "";
    in-out property <string> error-message: "";
    in-out property <string> font-family: "";

    VerticalLayout {
        padding: 16px;
        spacing: 8px;

        input := LineEdit {
            text <=> root.text;
            placeholder-text: "Write a note…";

            font-size: 18px;
            font-family: root.font-family;

            accepted(text) => {
                root.save-note(text);
            }

            key-pressed(event) => {
                if event.text == Key.Escape {
                    root.cancel-note();
                    accept
                }
                reject
            }
        }

        if root.error-message != "": Text {
            text: root.error-message;
            color: #FFFFFF;
            font-size: 12px;
        }
    }

    focus-input() => {
        input.focus();
    }
}

export component LatchnottTray inherits SystemTrayIcon {
    icon: @image-url("../assets/tray.svg");
    tooltip: "Latchnott";
    visible: true;

    callback new-note();
    callback quit();

    Menu {
        MenuItem {
            title: "New note";

            activated => {
                root.new-note();
            }
        }

        MenuSeparator { }

        MenuItem {
            title: "Quit";

            activated => {
                root.quit();
            }
        }
    }
}
